var FlowCommPage={
		style:   '<style>'
				+'	.add-user-demo { margin: 0; padding: 0; width: 100%; overflow: auto; min-height: 34px; border: #ccc solid 1px; }'
				+'	.add-user-demo li { list-style: none; display: block; float: left; margin: 10px 10px 5px 0px; background: #3c8dbc; padding: 2px 10px; color: #fff; border-radius: 4px; cursor: default; }'
				+'	.add-user-demo li:first-child { margin-left: 10px;}'
				+'	.add-user-demo li i { cursor: pointer;}'
				+'	.hidden{display: none;}'
				+'	.xuanrenBox li { border-bottom: 1px solid #f4f4f4; margin-top: 0px;}'
				+'	.xuanrenBox li .msg { color: #444; font-size: 12px; }'
				+'	.xuanrenBox li .msg i { font-size: 16px; color: #444; }'
				+'	.xuanrenBox li .uesr { width: 30px; height: 30px; display: block; border-radius: 50%; float: left; line-height: 30px; margin-top: 4px; text-align: center; color: #fff; font-size: 10px;  }'
				+'	.xuanrenBox li .uesrName .uesrName1 { margin-left: 10px; font-size: 12px; }'
				+'	.xuanrenBox li .uesrName .uesrName2 { margin-left: 10px; font-size: 10px; font-weight: normal; }'
				+'	.xuanrenBox1 li { border-bottom: 1px solid #ccc;}'
				+'	.xuanrenBox1 li .uesr { width: 30px; height: 30px; display: block; border-radius: 50%; float: left; line-height: 30px; margin-top: 4px; text-align: center; color: #fff; font-size: 10px;  }'
				+'	.xuanrenBox1 li .uesrName .uesrName1 { margin-left: 10px; font-size: 12px; }'
				+'	.xuanrenBox1 li .uesrName .uesrName2 { margin-left: 10px; font-size: 10px; font-weight: normal; }'
				+'	.xuanrenBoxX li { border-bottom: 1px solid #ccc;}'
				+'	.xuanrenBoxX li .uesr { width: 30px; height: 30px; display: block; border-radius: 50%; float: left; line-height: 30px; margin-top: 4px; text-align: center; color: #fff; font-size: 12px;  }'
				+'	.xuanrenBoxX li .uesrName .uesrName1 { margin-left: 10px; font-size: 14px; }'
				+'	.xuanrenBoxX li .uesrName .uesrName2 { margin-left: 10px; font-size: 12px; font-weight: normal; }'
				+'	</style>'
		,content:'<section class="">'
				+'	<div class="row">'
				+'		<div class="col-md-12">'
				+'			<div class="box box-primary">'
				+'				<div class="box-header with-border">'
				+'	              <h3 class="box-title">流程表单</h3>'
				+'	              <div class="box-tools pull-right">'
				+'	                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>'
				+'	              </div>'
				+'	            </div>'
				+'				<div class="box-body" id="flow_comm_wrap_form_div" style="min-height: 300px;">'
				+'	            </div>'
				/*+'	            <div class="box-footer text-right">'
				+'	                 <button type="button" class="btn btn-default btn-sm" id="form_btn_cance_back" data-dismiss="modal">取消</button>'
				+'		             <button type="button" class="btn btn-primary btn-sm" id="nextApplyUser" onclick="openUserWin()">下一步办理人</button>'
				+'	            </div>'*/
				+'			</div>'
				+'		</div>'
				+'	</div>'
				+'	</section>',
		 content2:'<div class="box-footer text-right">'
			 	 +'	    <button type="button" class="btn btn-default btn-sm" id="form_btn_cance_back" data-dismiss="modal">取消</button>'
			 	 +'		<button type="button" class="btn btn-primary btn-sm" id="nextApplyUser" onclick="openUserWin()">下一步办理人</button>'
			 	 +'</div>'
		,signContent:	'<h4 class="sign_title"><i class="fa fa-commenting-o"></i> 会签意见区</h4>'
					   +'<ul class="sign">'
					   +'	  <li>'
					   +'		<p>'
					   +'			<strong>第2步[会签]&nbsp;二、填写培训需求</strong><span>2016-7-22 16:43</span>'
					   +'		</p>'
					   +'		<p>'
					   +'			<strong>会签人员意见&nbsp;张三：</strong>'
					   +'		</p>'
					   +'		<i>无借由器材</i>'
					   +'	</li>'
					   +'</ul>'
		,applyContent:'<h4 style="margin-top: 30px;" class="sign_title"><i class="fa fa-commenting-o"></i> 审核意见区</h4>'
					 +'<ul class="sign">'
					 +'	 <li>'
					 +'		<p>'
					 +'			<strong>第2步[审核]&nbsp;二、填写培训需求</strong><span>2016-7-22 16:43</span>'
					 +'		</p>'
					 +'		<p>'
					 +'			<strong>审核人员意见&nbsp;张三：</strong>'
					 +'		</p>'
					 +'		<i>无借由器材</i>'
					 +'	</li>'
					 +'</ul>'
		,flowContent:'<table class="flowPath">'
					+'	<thead>'
					+'		<tr>'
					+'			<th colspan="5" style="text-align: center;" id="flowPath_table_tr">流程开始(流水号：370000)</th>'
					+'		</tr>'
					+'	</thead>'
					+'	<tbody>'
					+'	</tbody>'
					+'</table>'
}